name: Deploy Jupyter Notebook to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Copy notebook to droplet
        run: |
          scp -o StrictHostKeyChecking=no example.ipynb ${{ secrets.DROPLET_USER }}@${{ secrets.IP }}:~/example.ipynb

      - name: Run notebook server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.IP }} << 'EOF'
            sudo apt update
            sudo apt install -y python3-pip
            pip3 install --upgrade pip
            pip3 install notebook pandas numpy matplotlib
            nohup jupyter notebook --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=~ > jupyter.log 2>&1 &
          EOF
