name: Deploy Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.IP }} << 'EOF'
            echo "[CI] Updating system (if needed)..."
            command -v python3 || (sudo apt update && sudo apt install -y python3)
            command -v pip3 || (sudo apt install -y python3-pip)

            echo "[CI] Installing Jupyter..."
            pip3 install --user notebook pandas numpy matplotlib

            echo "[CI] Killing old Jupyter if exists..."
            pkill -f "jupyter-notebook" || true

            echo "[CI] Starting Jupyter..."
            nohup ~/.local/bin/jupyter-notebook \
              --ip=0.0.0.0 \
              --port=8888 \
              --no-browser \
              --NotebookApp.token='' \
              --NotebookApp.password='' \
              --notebook-dir=~ > jupyter.log 2>&1 &

            echo "[CI] Jupyter started on port 8888"
          EOF
