name: Deploy Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Copy notebook to droplet
        run: |
          scp -o StrictHostKeyChecking=no example.ipynb ${{ secrets.DROPLET_USER }}@${{ secrets.IP }}:~/example.ipynb

      - name: Run Jupyter Notebook on droplet (no sudo)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.IP }} << 'EOF'
            pip3 install --user --upgrade pip
            pip3 install --user notebook pandas numpy matplotlib
            pkill -f "jupyter-notebook" || true
            nohup ~/.local/bin/jupyter-notebook \
              --ip=0.0.0.0 \
              --port=8888 \
              --no-browser \
              --NotebookApp.token='' \
              --NotebookApp.password='' \
              --notebook-dir=~ > jupyter.log 2>&1 &
          EOF
